# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=245, null=True)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('valid_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('occupation', models.CharField(choices=[('PHOTOGRAPHER', 'PHOTOGRAPHER'), ('FASHION STYLIST', 'FASHION STYLIST'), ('INDUSTRY PROFESSIONAL', 'INDUSTRY PROFESSIONAL'), ('HAIR AND MAKE UP ARTIST', 'HAIR AND MAKE UP ARTIST')], max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20)),
                ('height', models.IntegerField(choices=[(190, '190cm'), (185, '185cm'), (180, '180cm'), (175, '175cm'), (170, '170cm')], default=0)),
                ('gender', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=7)),
                ('location', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru')], max_length=245)),
                ('image', models.ImageField(upload_to='photolook')),
                ('profile_pic', models.ImageField(null='True', upload_to='profile_pic')),
                ('occupation', models.CharField(choices=[('MODEL', 'MODEL')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='casting',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Model'),
        ),
    ]
