# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic'),
        ),
    ]
