# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('occupation', models.CharField(choices=[('PHOTOGRAPHER', 'PHOTOGRAPHER'), ('FASHION STYLIST', 'FASHION STYLIST'), ('INDUSTRY PROFESSIONAL', 'INDUSTRY PROFESSIONAL'), ('HAIR AND MAKE UP ARTIST', 'HAIR AND MAKE UP ARTIST')], max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
