# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('valid_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Client')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='photolook',
            field=models.ImageField(default=1, upload_to='photolook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Model'),
        ),
    ]
