# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_client_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model',
            new_name='user',
        ),
    ]
