# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20190116_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='photolook',
            new_name='image',
        ),
        migrations.AddField(
            model_name='model',
            name='occupation',
            field=models.CharField(choices=[('MODEL', 'MODEL')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='profile_pic',
            field=models.ImageField(null='True', upload_to='profile_pic'),
        ),
    ]
