# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20190116_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='casting',
            name='Title',
            field=models.CharField(max_length=245, null=True),
        ),
    ]
